Conv2D_config_template = {
    'name': '_node_name',
    'class_name': 'Conv2D',
    'config': {'name': '_node_name',
    'trainable': True,
    'dtype': 'float32',
    'filters': 1,
    'kernel_size': (1, 1),
    'strides': (1, 1),
    'padding': 'same',
    'data_format': 'channels_last',
    'dilation_rate': (1, 1),
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None},
   'name': '_node_name',
   'inbound_nodes': [[['_in_node_name', 0, 0, {}]]]}

DepthwiseConv2D_config_template = {'name': '_node_name',
 'class_name': 'DepthwiseConv2D',
 'config': {'name': '_node_name',
  'trainable': True,
  'dtype': 'float32',
  'kernel_size': (3, 3),
  'strides': (1, 1),
  'padding': 'same',
  'data_format': 'channels_last',
  'dilation_rate': (1, 1),
  'activation': 'linear',
  'use_bias': False,
  'bias_initializer': {'class_name': 'Zeros', 'config': {'dtype': 'float32'}},
  'bias_regularizer': None,
  'activity_regularizer': None,
  'bias_constraint': None,
  'depth_multiplier': 1,
  'depthwise_initializer': {'class_name': 'GlorotUniform',
   'config': {'seed': None, 'dtype': 'float32'}},
  'depthwise_regularizer': None,
  'depthwise_constraint': None},
 'inbound_nodes': [[['_in_node_name', 0, 0, {}]]]}